apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-stable
spec:
  replicas: 9
  selector:
    matchLabels:
      app: shop-canary
  template:
    metadata:
      labels:
        app: shop-canary
        version: stable
        track: stable
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo:1.0
          args: ["-listen=:8080", "-text=stable v1"]
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3
